import { delay } from './util'
export function getInitData() {
    return delay({
        top: [
            {
                'title': '需求',
                'key': '需求',
                'icon': 'icon-xuqiu',
                'url': '#/diyDetail?isTest=1',
                'value': ''
            },
            {
                'title': '任务',
                'key': '任务',
                'icon': 'icon-renwu',
                'url': '#/diyDetail?isTest=1',
                'value': ''
            },
            {
                'title': '日报',
                'key': '日报',
                'icon': 'icon-shengpi',
                'url': '#/diyDetail?isTest=1',
                'value': ''
            }
        ],
        body: [
            {
                'title': '植保管理',
                'items': [{
                    'title': '需求',
                    'icon': 'icon-xuqiu',
                    'url': '/pm/#!/agri/list?src=/wechat/mars/contract/my_contracts',
                    'value': '8',
                    'visible': true,
                    'key': '需求',
                    'update': 1
                }, {
                    'title': '任务',
                    'icon': 'icon-renwu',
                    'url': '/pm/#!/agri/list?src=/wechat/schedule/task/tmp_my_tasks',
                    'value': '2',
                    'visible': true,
                    'key': '任务',
                    'update': 1
                }, {
                    'title': '日报',
                    'icon': 'icon-shengpi',
                    'url': '/pm/#!/agri/list/?src=/wechat/schedule/report/tmp_wf_index',
                    'value': '1',
                    'visible': true,
                    'key': '日报',
                    'update': 1
                }, {
                    'title': '绩效',
                    'icon': 'icon-tongji',
                    'url': '/pm/#!/agri/detail/?src=/wechat/schedule/reward/tmp_detail',
                    'value': '',
                    'visible': true,
                    'key': '绩效'
                }, {
                    'title': '团队',
                    'icon': 'icon-kehu',
                    'url': '/pm/#!/agri/groupList/?src=/wechat/account/group/my_spray_group_list',
                    'value': '0',
                    'visible': true,
                    'key': '团队'
                }, {
                    'title': '设备',
                    'icon': 'icon-cubelifangti',
                    'url': '/pm/#!/agri/list?src=/wechat/equipment/home/my_equipments',
                    'value': '',
                    'visible': true,
                    'key': '设备'
                }, {
                    'title': '天气',
                    'icon': 'icon-tianqi',
                    'url': '/pm/#!/weather',
                    'value': '',
                    'visible': true,
                    'key': '天气'
                }, {
                    'title': '保障',
                    'icon': 'icon-x_protection1',
                    'url': '/pm/#!/agri/list?src=/wechat/protection/service/home/index',
                    'value': '',
                    'visible': true,
                    'key': '保障'
                }, {
                    'title': '沙盘',
                    'icon': 'icon-weizhi',
                    'url': '/pm/#!/monitor/wcoverview/?src=/wechat/monitor/sand/settings',
                    'value': '',
                    'visible': true,
                    'key': '沙盘'
                }, {
                    'title': '保险',
                    'icon': 'icon-baozhang',
                    'url': '/pm/#!/agri/list?src=/wechat/protection/insurance/index',
                    'value': '',
                    'visible': true,
                    'key': '保险'
                }, {
                    'title': '反馈',
                    'icon': 'icon-tousujianyi',
                    'url': '/pm/#!/agri/list?src=/wechat/complaint/home/index',
                    'value': '',
                    'visible': true,
                    'key': '反馈'
                }, {
                    'title': '推广',
                    'icon': 'icon-tuiguang',
                    'url': '/pm/#!/agri/list?src=/wechat/market/demo/my_list',
                    'value': '',
                    'visible': true,
                    'key': '推广'
                }, {
                    'title': '联盟',
                    'icon': 'icon-lianmeng1',
                    'url': '/pm/#!/diyDetail/?src=/wechat/league/home/index',
                    'value': '',
                    'visible': true,
                    'key': '联盟'
                }, {
                    'title': '禁飞区',
                    'icon': 'icon-jinfeiqu',
                    'url': '/pm/#!/agri/list/?src=/wechat/noflyzone/home/my_list',
                    'value': '',
                    'visible': true,
                    'key': '禁飞区'
                }, {
                    'title': '农作物',
                    'icon': 'icon-zuowuquan-copy',
                    'url': '/pm/#!/diyDetail/?src=/wechat/collect/home/my_index_page',
                    'value': '',
                    'visible': true,
                    'key': '农作物'
                }, {
                    'title': '租赁',
                    'icon': 'icon-zulin',
                    'url': '/pm/#!/rent/index',
                    'value': '',
                    'visible': true,
                    'key': '租赁'
                }, {
                    'title': '统计',
                    'icon': 'icon-baobiao',
                    'url': '/pm/#!/diyDetail/?src=/wechat/admin/stat/index',
                    'value': '',
                    'visible': true,
                    'key': '统计'
                }, {
                    'title': '新疆战况',
                    'icon': 'icon-icon2',
                    'url': '/pm/#!/diyDetail/?src=/wechat/mars/act/index',
                    'value': '',
                    'visible': true,
                    'key': '新疆战况'
                },
                {
                    'title': '信用',
                    'icon': 'icon-xinyong',
                    'url': '/pm/#!/credit',
                    'value': '',
                    'visible': true,
                    'key': '信用'
                },
                {
                    'title': '农事',
                    'icon': 'icon-nongshi4',
                    'url': '#/main?isTest=1&src=farming',
                    'value': '',
                    'visible': true,
                    'key': '农事'
                }
                ],
                'key': '植保管理',
                'visible': true
            }, {
                'title': '销售管理',
                'items': [{
                    'title': '销售订单',
                    'icon': 'icon-icon-pin',
                    'url': '/pm/#!/diyForm?src=/wechat/erp/order/search_page',
                    'value': '',
                    'visible': true,
                    'key': '销售订单'
                }],
                'key': '销售管理',
                'visible': true
            }, {
                'title': '管理功能',
                'items': [{
                    'title': '反馈处理',
                    'icon': 'icon-tousu1',
                    'url': '/pm/#!/agri/list?src=/wechat/complaint/handle/index',
                    'value': '70',
                    'visible': true,
                    'key': '反馈处理'
                }, {
                    'title': '推广审核',
                    'icon': 'icon-tuiguang',
                    'url': '/pm/#!/agri/list?src=/wechat/market/confirm/confirm_list',
                    'value': '3',
                    'visible': true,
                    'key': '推广审核'
                }, {
                    'title': '农作物审核',
                    'icon': 'icon-zuowuquan-copy',
                    'url': '/pm/#!/agri/list/?src=/wechat/collect/home/confirm_list',
                    'value': '3',
                    'visible': true,
                    'key': '农作物审核'
                }, {
                    'title': '禁飞区审核',
                    'icon': 'icon-jinfeiqu',
                    'url': '/pm/#!/agri/list/?src=/wechat/noflyzone/home/confirm_list',
                    'value': '2',
                    'visible': true,
                    'key': '禁飞区审核'
                }, {
                    'title': '认证管理',
                    'icon': 'icon-renzheng',
                    'url': '/pm/#!/agri/list?src=/wechat/account/identification/verify_index',
                    'value': '0',
                    'visible': true,
                    'key': '认证管理'
                }],
                'key': '管理功能',
                'visible': true
            }, {
                'title': '极飞学院管理',
                'items': [{
                    'title': '培训网点',
                    'icon': 'icon-wangdianmingcheng',
                    'url': '/pm/#!/agri/list?src=/wechat/train/station/index',
                    'value': '',
                    'visible': true,
                    'key': '培训网点'
                }, {
                    'title': '科目B管理',
                    'icon': 'icon-caogaoxiang',
                    'url': '/pm/#!/agri/list?src=/wechat/course/outline/index',
                    'value': '',
                    'visible': true,
                    'key': '科目B管理'
                }, {
                    'title': '款项审核',
                    'icon': 'icon-duihuan',
                    'url': '/pm/#!/agri/list?src=/wechat/train/money/index',
                    'value': '',
                    'visible': true,
                    'key': '款项审核'
                }, {
                    'title': '科目B审核',
                    'icon': 'icon-hetong',
                    'url': '/pm/#!/agri/list?src=/wechat/course/admin/index',
                    'value': '0',
                    'visible': true,
                    'key': '科目B审核'
                }, {
                    'title': '我的培训网点',
                    'icon': 'icon-jiaoyupeixun',
                    'url': '/pm/#!/agri/list?src=/wechat/train/manage/index',
                    'value': '',
                    'visible': true,
                    'key': '我的培训网点'
                }],
                'key': '极飞学院管理',
                'visible': true
            }, {
                'title': '教员',
                'items': [{
                    'title': '我的培训点',
                    'icon': 'icon-jieshou',
                    'url': '/pm/#!/agri/detail?src=/wechat/train/teacher/my_train_station',
                    'value': '',
                    'visible': true,
                    'key': '我的培训点'
                }, {
                    'title': '接收学员',
                    'icon': 'icon-xinzengxueyuan',
                    'url': '/pm/#!/agri/createQRCode?src=/wechat/train/student/join_qr_code&params={train_station_teacher_uid:AE1996A7449C22CE31011EBB06DED87A}',
                    'value': '',
                    'visible': true,
                    'key': '接收学员'
                }, {
                    'title': '我的学员',
                    'icon': 'icon-wodexueyuan',
                    'url': '/pm/#!/agri/list?src=/wechat/train/teacher/my_students',
                    'value': '',
                    'visible': true,
                    'key': '我的学员'
                }],
                'key': '教员',
                'visible': true
            }, {
                'title': '极飞保障',
                'items': [{
                    'title': '保障核损',
                    'icon': 'icon-cubelifangti',
                    'url': '/pm/v4/#/diyList?src=%2Fwechat%2Fv4%2Fprotection%2Fservice%2Fverify',
                    'value': '',
                    'visible': true,
                    'key': '保障核损'
                }, {
                    'title': '临时使用权',
                    'icon': 'icon-cubelifangti',
                    'url': '/pm/#!/diyForm?src=/wechat/safeguard/provisional/frm_apply',
                    'value': '',
                    'visible': true,
                    'key': '临时使用权'
                }, {
                    'title': '保障经理管理',
                    'icon': 'icon-shichangjingli',
                    'url': '/pm/#!/agri/list?src=/wechat/protection/manager',
                    'value': '',
                    'visible': true,
                    'key': '保障经理管理'
                }, {
                    'title': '总监审核',
                    'icon': 'icon-quyushenhe',
                    'url': '/pm/#!/agri/detail?src=/wechat/protection/verify/manager_index',
                    'value': '',
                    'visible': true,
                    'key': '总监审核'
                }, {
                    'title': '保障仓管理',
                    'icon': 'icon-group-warehouse',
                    'url': '/pm/#!/agri/list?src=/wechat/protection/warehouse/group_index',
                    'value': '',
                    'visible': true,
                    'key': '保障仓管理'
                }, {
                    'title': '我的保障仓库',
                    'icon': 'icon-kucunguanli',
                    'url': '/pm/#!/diyDetail/?src=/wechat/protection/manage/detail',
                    'value': '',
                    'visible': true,
                    'key': '我的保障仓库'
                }, {
                    'title': '设备查询',
                    'icon': 'icon-cubelifangti',
                    'url': '/pm/#!/diyForm/?src=/wechat/equipment/home/equipment_search',
                    'value': '',
                    'visible': true,
                    'key': '设备查询'
                }, {
                    'title': '保障仓库管理',
                    'icon': 'icon-icon-storage2',
                    'url': '/pm/#!/agri/list?src=/wechat/protection/warehouse/index',
                    'value': '',
                    'visible': true,
                    'key': '保障仓库管理'
                }, {
                    'title': '保障经理审核',
                    'icon': 'icon-quyushenhe',
                    'url': '/pm/#!/agri/detail?src=/wechat/protection/verify/region_index',
                    'value': '',
                    'visible': true,
                    'key': '保障经理审核'
                }, {
                    'title': '区域作业统计',
                    'icon': 'icon-tongji',
                    'url': '/pm/#!/diyDetail?src=/wechat/admin/city/provinces',
                    'value': '',
                    'visible': true,
                    'key': '区域作业统计'
                }, {
                    'title': '物料申请',
                    'icon': 'icon-liangfanzhuang',
                    'url': '/pm/#!/agri/list?src=/wechat/protection/material/manager/index',
                    'value': '0',
                    'visible': true,
                    'key': '物料申请'
                }, {
                    'title': '物料申请审核',
                    'icon': 'icon-approve',
                    'url': '/pm/#!/agri/list?src=/wechat/protection/material/admin/index',
                    'value': '',
                    'visible': true,
                    'key': '物料申请审核'
                }, {
                    'title': '保障先锋',
                    'icon': 'icon-approve',
                    'url': '/pm/#!/agri/detail?src=/wechat/protection/pioneer/home/index',
                    'value': '',
                    'visible': true,
                    'key': '保障先锋'
                }, {
                    'title': '更换零部件',
                    'icon': 'icon-cubelifangti',
                    'url': '/pm/#!/diyForm/?src=/wechat/equipment/manager/exchange',
                    'value': '',
                    'visible': true,
                    'key': '更换零部件'
                }],
                'key': '极飞保障',
                'visible': true
            }
        ],
        visibleApi: 'isTest',
        sortApi: 'isTest',
        valueApi: 'isTest'
    })
}

export function visiableChange(params) {
    console.log('visiableChange:params', JSON.stringify(params))
    return delay({})
}

export function sortChange(params) {
    console.log('sortChange:params', JSON.stringify(params))
    return delay({})
}

export function valueChange(params) {
    console.log('valueChange:params', JSON.stringify(params))
    let result = params.data.data
    for (var key in result) {
        result[key] = parseInt(Math.random() * 40 % 40)
    }
    return delay(result)
}